# CI 项目
name: clean-all

# CI 权限
permissions: write-all

# CI 计划
on:
  # 手动运行
  workflow_dispatch:
    inputs:
      CONFIRM:
        description: '确认清理数据'
        required: true
        type: boolean
        default: false
      RELEASES:
        description: '[CleanReleases]'
        required: true
        type: boolean
        default: true
      CACHE:
        description: '[CleanCache]'
        required: true
        type: boolean
        default: true
  # 工作流调用
  workflow_call:

# CI 环境
env:
  # GITHUB ENV
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  # CI ENV
  CI_CleanConfirm: ${{inputs.CONFIRM}}
  CI_CleanReleases: ${{inputs.RELEASES}}
  CI_CleanCache: ${{inputs.CACHE}}

# CI 任务
jobs:
  clean-all:
    name: clean-all
    runs-on: ubuntu-latest
    steps:
      - name: IsConfirm
        run: |
          if [[ "$CI_CleanConfirm" == 'false' ]]; then
            echo 'Error: Please confirm deletion'
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@main

      - name: DeleteReleases
        if: env.CI_CleanReleases == 'true'
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_tags: true
          delete_releases: true
          releases_keep_latest: 0
          releases_keep_keyword: ''
          delete_workflows: true
          workflows_keep_day: 0
          workflows_keep_keyword: ''

      - name: CleanCache
        if: env.CI_CleanCache == 'true'
        run: gh cache delete --all
